### ISSUE TITLE
[BUG] jackson "LocalDate" serialialization doesn't work

### ISSUE THREAD

**Issue by Mael-Chemeque** [kangaroo-and-rabbit/archidata#23]
As seen in this blog: [Jackson Java 8 Date Time Type – java.time.LocalDate not supported by default](https://mkyong.com/java/jackson-java-8-date-time-type-java-time-localdate-not-supported-by-default/), it's necessary to register the JavaTimeModule() with the ObjectMapper to handle java.time classes like LocalDate, LocalDateTime, etc.

This can be done as follows:

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JavaTimeModule());
```

**Comment by EdouardDUPIN** [comment]
Fixed by: https://github.com/kangaroo-and-rabbit/archidata/commit/01560cd2852eafa8125fd646619965fa6c9a02e4

need to call in the configuration: 
```java
ContextGenericTools.addJsr310(rc);
```

cf: https://github.com/kangaroo-and-rabbit/archidata/blob/01560cd2852eafa8125fd646619965fa6c9a02e4/test/src/test/kar/archidata/apiExtern/WebLauncher.java#L118

not tested, but in the timestamp mabe no more need of 
```
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")
```
